#' Toy data for feature selection
#'
#' A dataset containing the prices and other attributes of almost 54,000
#' diamonds.
#'
#' @format A data frame with :
#' \describe{
#' }
#' @source Generated by MCMC sampling
"toy_data"